### ISSUE TITLE
Errors building klksd on Ubuntu 18.04

### ISSUE THREAD

**Issue by iSnow** [kalkulusteam/klks#13]
Trying to build HEAD from git leads to the following errors: 

	Making all in src
	make[1]: Entering directory '/home/isnow/klks/src'
	make[2]: Entering directory '/home/isnow/klks/src'
	usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
	  limiting output:
		--max-count=<n>
		--max-age=<epoch>
		--min-age=<epoch>
		--sparse
		--no-merges
		--min-parents=<n>
		--no-min-parents
		--max-parents=<n>
		--no-max-parents
		--remove-empty
		--all
		--branches
		--tags
		--remotes
		--stdin
		--quiet
	  ordering output:
		--topo-order
		--date-order
		--reverse
	  formatting output:
		--parents
		--children
		--objects | --objects-edge
		--unpacked
		--header | --pretty
		--abbrev=<n> | --no-abbrev
		--abbrev-commit
		--left-right
		--count
	  special purpose:
		--bisect
		--bisect-vars
		--bisect-all
	make[3]: Entering directory '/home/isnow/klks/src/secp256k1'
	make[3]: *** No rule to make target 'libsecp256k1.la'.  Stop.
	make[3]: Leaving directory '/home/isnow/klks/src/secp256k1'
	Makefile:7529: recipe for target 'secp256k1/libsecp256k1.la' failed
	make[2]: *** [secp256k1/libsecp256k1.la] Error 2
	make[2]: Leaving directory '/home/isnow/klks/src'
	Makefile:7034: recipe for target 'all-recursive' failed
	make[1]: *** [all-recursive] Error 1
	make[1]: Leaving directory '/home/isnow/klks/src'
	Makefile:595: recipe for target 'all-recursive' failed
	make: *** [all-recursive] Error 1

Before compilation, the following libs and dependencies were installed: 

	sudo apt install -y libboost-all-dev
	sudo apt install -y build-essential libtool autotools-dev automake autogen autoconf pkg-config libssl-dev libevent-dev bsdmainutils
	sudo apt install -y git gcc libsecp256k1-dev libzmq3-dev libdb4.8-dev libdb4.8++-dev libqrencode-dev
	sudo apt install -y libssl1.0-dev python-virtualenv

	sudo apt-add-repository ppa:bitcoin/bitcoin
	sudo apt update && sudo apt install -y bitcoin-qt

Before issuing "make", the following commands were run:

`libtoolize && aclocal && autoheader && autoconf && automake`

**Comment by kalkulusteam** [comment]
Hello,
try compiling starting from step 2 reported on this page
[http://kalkulus.trade/manual-installation](url)

Be sure to have following installed for compile QT wallet:
`sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libzmq3-dev`

**Comment by kalkulusteam** [comment]
Closing issue, no follow up.

**Comment by iSnow** [comment]
Did someone at your site try the guide with Ubuntu 18.04? I cannot really believe anyone did, as  apt  reports:

    Package python-software-properties is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or is only available from another source
    However the following packages replace it:
        software-properties-common

This, of course is not fatal, but later make gives me in the configure step: 
     configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!
     Makefile:544: recipe for target 'config.status' failed
     make: *** [config.status] Error 1

**Comment by iSnow** [comment]
I think you need to look at https://github.com/PIVX-Project/PIVX/pull/447 - they fixed the libre/openssl problems a year ago.

**Comment by kalkulusteam** [comment]
If you want to contribute you are welcome
Thanks

Il giorno mar 18 dic 2018 alle ore 11:16 Johannes Jander <
notifications@github.com> ha scritto:

**Comment by iSnow** [comment]
That does not answer my questions. I am no crypto dev, I cannot contribute in any other way than raising tickets.

**Comment by kalkulusteam** [comment]
Ok , as we said in previous messages we will fix that very soon.Thanks

Il giorno mar 18 dic 2018 alle ore 12:36 Johannes Jander <
notifications@github.com> ha scritto:

**Comment by iSnow** [comment]
Seems like installing `libssl1.0-dev` fixed the problems.

**Comment by qwrtyasdfg** [comment]
Looks like you already had this installed, as reported on your first post.
By the way, glad that worked.

**Comment by kalkulusteam** [comment]
Thanks a lot, we will add that in the list of needed deps.
Def closing issue.
